config/routes.rb
Rails.application.routes.draw do
  get 'welcome/sample'

  #match 'controller(/:action(/:id))', :via => :get

  resources :projects do
  	resources :tasks
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :name, presence: true,
            length: { minimum: 4 }
end

app/models/task.rb
class Task < ApplicationRecord
   belongs_to :project
   has_many :users, dependent: :destroy
   validates :status, inclusion: { in: %w(new inprogress done),
                                   message: "there is could be enum(new,in_progress,done)"}
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :task
  validates :first_name, length: { minimum: 2 }
  validates :last_name, length: { minimum: 2 }
  validates :password, length: { minimum: 8 }
  validates :admin, inclusion: { in: %w(true false) ,
                                 message: "true/false please" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.all
	end

	def show
		@project = Project.find(params[:id])
	end

	def new
		@project = Project.new
	end

	def edit
		@project = Project.find(params[:id])
	end

	def create
		@project = Project.new(project_params)

		if @project.save
			redirect_to @project
		else
			render 'new'
		end
	end

	def update
		@project = Project.find(params[:id])

		if @project.update(project_params)
			redirect_to @project
		else
			render 'edit'
		end
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy

		redirect_to projects_path
	end

	private
	def project_params

		params.require(:project).permit(:name, :summary, :start_date, :end_date)


	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def edit
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
  end

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def update
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])

    if @task.update(task_params)
      redirect_to @project
    else
      render 'edit'
    end
  end


  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    @task.destroy
    redirect_to project_path(@project)
  end

  private
  def task_params
    params.require(:task).permit(:title, :description, :status)
  end


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
    @task = Task.find(params[:task_id])
    @project = Project.find(params[:project_id])
  end

  def create
    @project = Project.find(params[:project_id])
    @task = Task.find(params[:task_id])
    @user = @task.users.create(user_params)
    if @task.save
      redirect_to @project
    else
      render 'new'
    end
  end


  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])

    redirect_to project_path(@project)
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :admin)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: @project, local: true) do |form| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :summary %><br>
    <%= form.text_area :summary %>
  </p>

  <p>
    <%= form.label :start_date %><br>
    <%= form.date_field :start_date %>
  </p>

  <p>
    <%= form.label :end_date %><br>
    <%= form.date_field :end_date %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/projects/edit.html.erb
<h1>Edit project</h1>
<%= render 'form' %>
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% if @project.any? %>
<h1>Listing projects</h1>

<%= link_to 'Create new project', new_project_path %>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Summary</th>
    <th>Start date</th>
    <th>End date</th>
    <th></th>
  </tr>

  <% @projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.summary %></td>
      <td><%= link_to 'Show', project_path(project) %></td>
      <td><%= link_to 'Edit', edit_project_path(project) %></td>
      <td><%= link_to 'Destroy', project_path(project),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
  <%= link_to 'Create project', new_project_path %>
  </p>
<% else %>
  <%= link_to 'Create project', new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>
<%= render 'form' %>
<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Text:</strong>
  <%= @project.summary %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>
<p>
  <strong>End date:</strong>
  <%= @project.end_date %>
</p>

<% if @project.tasks.any? %>
  <h2>Tasks</h2>

  <table  class="table table-striped">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @project.tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td>| <%= link_to 'Edit task', edit_project_task_path(task) %> |</td>
        <td>| <%= link_to 'Destroy task', [task.project, task],
                          method: :delete,
                          data: { confirm: 'Are you sure?' } %> |</td>
        <td>| <%= link_to 'Show users', project_task_path(task) %> |</td>
      </tr>
    <% end %>
  </table>


  <td><%= link_to 'Create task', new_project_task_path(@project) %> |</td>
  <td><%= link_to 'Back', projects_path %></td>
<% else %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, "error") %> prohibited
        this task from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <td><%= link_to 'Create task', new_project_task_path(@project) %> |</td>
  <td><%= link_to 'Back', projects_path %></td>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model: [ @project, @task], local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2 class="text-center">
        <%= pluralize(@task.errors.count, "error") %> prohibited
        this task from being saved:
      </h2>
      <ul class="text-center">
        <% @task.errors.full_messages.each do |msg| %>
          <li class="text-center"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.label :status %><br>
    <%= form.text_field :status %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/tasks/edit.html.erb
<h2>Edit task:</h2>
<%= render 'form' %>
<p><%= link_to 'Back', projects_path %></p>

app/views/tasks/new.html.erb
<h2>Create a new task:</h2>
<%= render 'form' %>
<p><%= link_to 'Back', projects_path %></p>

app/views/tasks/show.html.erb
<h1>Task details</h1>
<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>
<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<h2>Users</h2>

<% if @task.users.any? %>
<table class="table table-striped">
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Password</th>
    <th>Admin</th>
  </tr>

  <% @task.users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      <td><%= user.password %></td>
      <td><%= user.admin %></td>
    </tr>
  <% end %>
</table>

<td><%= link_to 'Add user', new_project_task_user_path(@project,@task) %> |</td>
<td><%= link_to 'Back', projects_path %></td>
<% else %>
  <td><%= link_to 'Add user', new_project_task_user_path(@project,@task) %> |</td>
  <td><%= link_to 'Back', projects_path %></td>
<% end %>

app/views/user/new.html.erb
<%= form_with(model: [ @project,@task, @task.users.build], local: true) do |form| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2 class="text-center">
        <%= pluralize(@task.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>
  <p>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
  </p>
  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>
  <p>
    <%= form.label :password %><br>
    <%= form.text_field :password %>
  </p>
  <p>
    <%= form.label :admin %><br>
    <%= form.text_field :admin %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<p><%= link_to 'Back', projects_path %></p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>


<%= "Count to 10"%>

<br />

<% 11.times do |i| %>
	<%= i %>
<% end %>

app/views/welcome/sample.html.erb
<h1>Welcome#Sample</h1>
<p>Find me in app/views/welcome/sample.html.erb</p>